services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb:/data/configdb
      - ./docker/mongodb:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./docker/mongodb/password.env
    restart: "no"
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://localhost:27017/admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  falkordb:
    image: falkordb/falkordb-server:v4.16.1-alpine
    container_name: falkordb-local
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - falkordb_data:/var/lib/falkordb/data
      - falkordb_redis_data:/data
      - ./docker/falkordb/fkdb_users.acl:/etc/redis/fkdb_users.acl:ro
    environment:
      REDIS_ARGS: "--aclfile /etc/redis/fkdb_users.acl"
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:8.4.0-alpine3.22
    container_name: redisdb-local
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - redis_data:/data
      - ./docker/redisdb/redis_users.acl:/etc/redis/redis_users.acl:ro
    command: ["redis-server", "--aclfile", "/etc/redis/redis_users.acl"]
    restart: "no"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
    name: mongodb_data
  mongodb_configdb:
    name: mongodb_configdb
  falkordb_data:
    name: falkordb_data
  falkordb_redis_data:
    name: falkordb_redis_data
  redis_data:
    name: redis_data

