services: # configure secrets from .env for local
  rstn-misr-etl-codebase:
    image: rstn-misr-etl-codebase:v0.1.0-trixie
    container_name: rstn-misr-etl-codebase
    ports:
      - "127.0.0.1:8001:8001"

    env_file:
      - .env

    environment:
      ETL_MONGO_HOST: mongodb-local
      ETL_REDIS_HOST: redisdb-local
      ETL_REDIS_PORT: 6379
      ETL_FALKOR_HOST: falkordb-local
      ETL_FALKOR_PORT: 6379

    networks:
      - shared_net

    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 750M

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import json,urllib.request,sys;sys.exit(0 if json.load(urllib.request.urlopen('http://localhost:8001/health'))['status']=='ok' else 1)",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1s

networks:
  shared_net:
    external: true
    name: freelance_p-01_cuisine-menu-recommendation-app_default
